language: c

compiler:
  - gcc

before_script:
  - wget http://heanet.dl.sourceforge.net/project/swig/swig/swig-2.0.11/swig-2.0.11.tar.gz
  - tar xzf swig-2.0.11.tar.gz
  - cd swig-2.0.11/ && ./configure --prefix=/usr && make && sudo make install
  - cd ../
  - sudo apt-get update -qq
  - sudo apt-get install -y tshark check rsync libpcap-dev gawk libedit-dev libpcre3-dev uuid-dev valgrind
  - mkdir workspace
  - cd workspace
  - cmake ../

script: make tests
